defaults:
  - data: default_paths
  - infer: checkpoint_path
  - logger:
      - csv_logger
      - mlflow_logger
  - model: distilbert
  - python_logging: setup
  - train: default
  - trainer: default
  - _self_
